In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame as df

In [6]:
# Reading in .csv
phys_para = pd.read_csv('reference_population.csv',
                      skiprows = [0,1,2,3], # Skipping extraneous rows
                      index_col = 'index')

In [7]:
phys_para

,mass,a,e,inc,varpi,Omega,M,ra,dec,R,rad,albedo,V,ZTF,DES,PS1
index,,,,,,,,,,,,,,,,
0,4.84,249.58,0.074,12.50,252.85,48.03,72.60,340.9044,-21.0693,245.34,1.61,0.270,19.39,1,0,1
1,7.54,375.45,0.232,14.13,237.85,111.55,55.36,322.4211,-21.4985,342.36,2.51,0.483,19.24,1,0,1
2,10.62,944.92,0.502,18.60,237.12,95.17,71.09,12.2508,-14.9859,1022.87,3.54,0.732,22.80,0,0,0
3,5.34,517.69,0.605,20.88,229.64,94.30,204.74,59.7006,7.9102,819.32,1.78,0.694,23.39,0,0,0
4,5.13,337.08,0.083,17.94,251.60,68.47,134.16,34.8625,2.8018,357.57,1.71,0.343,20.64,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,7.03,358.59,0.337,7.15,249.31,114.86,328.08,189.2720,3.4380,274.30,2.34,0.412,18.61,1,0,1
99996,9.03,692.75,0.382,14.90,235.17,120.02,280.20,114.3980,19.6485,744.28,3.01,0.731,21.78,0,0,0
99997,4.67,295.85,0.089,16.64,242.69,106.49,156.96,46.2160,2.0032,320.40,1.56,0.440,20.10,1,0,1
99998,10.54,425.21,0.194,11.41,249.82,111.51,146.16,47.2093,6.9098,497.83,3.51,0.408,20.33,1,0,1
99999,6.15,319.60,0.211,6.25,257.06,124.64,68.71,352.4977,-8.0657,308.63,2.05,0.373,19.52,1,0,1

In [8]:
# Copy phys_para to manipulate
para_copy = phys_para[[" V"]].copy()
para_copy = para_copy.rename(columns={' V': 'H'})   # Changed variable apparent mag to absolute mag
                                                    # Placeholder until Oorb is working
    
# Changing V mag to H mag column
para_copy["H"] -= 20 # Temporary change to change H mag to be detectable
##df["H"] = compute_H_mag(df)
##del df[" V"]

# Adding ObjID column
para_copy["ObjID"] = 't' + para_copy.index.astype(str) # Must change index to a string to add 't'
para_copy = para_copy[["ObjID", "H"]]

# Set value for colors
para_copy["u-r"] = 1.72 
para_copy["g-r"] = 0.48 
para_copy["i-r"] = -0.11 
para_copy["z-r"] = -0.12
para_copy["y-r"] = -0.12
para_copy["GS"] = 0.15
# Actual color values will be provided at later date

# Creates .txt file
para_copy.to_csv('phys_par.txt', index=False, sep=' ', float_format='%.2f')

In [9]:
! head phys_par.txt

ObjID H u-r g-r i-r z-r y-r GS
t0 -0.61 1.72 0.48 -0.11 -0.12 -0.12 0.15
t1 -0.76 1.72 0.48 -0.11 -0.12 -0.12 0.15
t2 2.80 1.72 0.48 -0.11 -0.12 -0.12 0.15
t3 3.39 1.72 0.48 -0.11 -0.12 -0.12 0.15
t4 0.64 1.72 0.48 -0.11 -0.12 -0.12 0.15
t5 0.19 1.72 0.48 -0.11 -0.12 -0.12 0.15
t6 -0.93 1.72 0.48 -0.11 -0.12 -0.12 0.15
t7 1.02 1.72 0.48 -0.11 -0.12 -0.12 0.15
t8 0.15 1.72 0.48 -0.11 -0.12 -0.12 0.15